server:
  port: 8082

config:
  data1: "K-PaaS is an open cloud platform created through collaborations with various domestic companies with the support of the National Information society Agency (NIA), to strengthen domestic IT services competitiveness in the cloud platform market concentrated in overseas companies."
  data2: "developed countries are paying attention to the cloud market, especially to platform services, and are in the process of adopting and spreading the government standard cloud platform using open source-based PaaS. In addition, the cloud PaaS platform is in fierce competition for market dominance, centered on global companies around the world."